# trigger is ommitted as per https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#ci-triggers this resolves to all branches (*)

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: "Copy $(sourceFolder) to artifact staging directory"
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'delta-cli'
        publishLocation: 'Container'
      displayName: "Publish Azure artifact"